// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class AdministrativeProcedure
{
    public int EmployeeNumber { get; set; }

    public bool? IsActive { get; set; }

    public string? OfficialLetter { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;
}