// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class BasicPoliceSkill
{
    public int EmployeeNumber { get; set; }

    public string? OfficialLetter { get; set; }

    public DateOnly? OfficialLetterDate { get; set; }

    public decimal? AverageGrade { get; set; }

    public bool? IsApproved { get; set; }

    public DateOnly? AcademicPerformanceEvaluationDate { get; set; }

    public int? AcademicPerformanceEvaluationScore { get; set; }

    public DateOnly? PerformanceEvaluationDate { get; set; }

    public int? PerformanceEvaluationScore { get; set; }

    public int? PoliceSkillStatusId { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;

    public virtual PoliceSkillStatus? PoliceSkillStatus { get; set; }
}