// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class CeccResult
{
    public int Id { get; set; }

    public int EmployeeNumber { get; set; }

    public string? OfficialLetter { get; set; }

    public DateOnly? OfficialLetterDate { get; set; }

    public bool? IsApproved { get; set; }

    public bool? IsInforce { get; set; }

    public DateOnly? SixMonthsBeforeExpirationDate { get; set; }

    public DateOnly? ExpirationDate { get; set; }

    public string? Notification { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;
}