// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class EccScheduling
{
    public int Id { get; set; }

    public int EmployeeNumber { get; set; }

    public string? OfficialLetterCeyCc { get; set; }

    public DateOnly? OfficialLetterCeyCcDate { get; set; }

    public string? OfficialLetterIfpes { get; set; }

    public DateOnly? OfficialLetterIfpesDate { get; set; }

    public DateTime? MedicalEvaluationDate { get; set; }

    public DateTime? SocioeconomicEnvironmentEvaluationDate { get; set; }

    public DateTime? ToxicologicalEvaluationDate { get; set; }

    public DateTime? PolygraphEvaluationDate { get; set; }

    public DateTime? PsychologicalEvaluationDate { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;
}