// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string? Rfc { get; set; }

    public string? Curp { get; set; }

    public string? Cuip { get; set; }

    public string? HighestEducationLevel { get; set; }

    public string? ProfessionalLicense { get; set; }

    public DateOnly? ProfessionalLicenseDate { get; set; }

    public string? Gender { get; set; }

    public string? PhoneNumber { get; set; }

    public string? Email { get; set; }

    public string? Address { get; set; }

    public string? Neighborhood { get; set; }

    public string? Zip { get; set; }

    public string? City { get; set; }

    public int? StateId { get; set; }

    public string? PhoneNumber2 { get; set; }

    public string? PhoneNumber3 { get; set; }

    public string? EmergencyContact { get; set; }

    public DateOnly? Birthdate { get; set; }

    public int? Height { get; set; }

    public int? MaritalStatusId { get; set; }

    public string? BirthPlace { get; set; }

    public int? ChildrenNumber { get; set; }

    public string? DriverLicense { get; set; }

    public string? LicenseType { get; set; }

    public int? LicenseIssuedStateId { get; set; }

    public DateOnly? LicenseIssuedDate { get; set; }

    public DateOnly? LicenseExpirationDate { get; set; }

    public bool? IsPermanentLicense { get; set; }

    public virtual AdministrativeProcedure? AdministrativeProcedure { get; set; }

    public virtual BasicPoliceSkill? BasicPoliceSkill { get; set; }

    public virtual ICollection<CeccResult> CeccResults { get; set; } = new List<CeccResult>();

    public virtual ICollection<EccRescheduling> EccReschedulings { get; set; } = new List<EccRescheduling>();

    public virtual ICollection<EccScheduling> EccSchedulings { get; set; } = new List<EccScheduling>();

    public virtual Incident? Incident { get; set; }

    public virtual InitialFormation? InitialFormation { get; set; }

    public virtual State? LicenseIssuedState { get; set; }

    public virtual MaritalStatus? MaritalStatus { get; set; }

    public virtual NationalMilitaryService? NationalMilitaryService { get; set; }

    public virtual PayrollRecord? PayrollRecord { get; set; }

    public virtual ICollection<PerformanceEvaluation> PerformanceEvaluations { get; set; } = new List<PerformanceEvaluation>();

    public virtual ICollection<RecruitmentNotice> RecruitmentNotices { get; set; } = new List<RecruitmentNotice>();

    public virtual ICollection<Resume> Resumes { get; set; } = new List<Resume>();

    public virtual State? State { get; set; }

    public virtual UniquePoliceCertificate? UniquePoliceCertificate { get; set; }
}