// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class Incident
{
    public int EmployeeNumber { get; set; }

    public int? Year { get; set; }

    public bool? HasIncident { get; set; }

    public string? OfficialLetterAreaIncident { get; set; }

    public string? OfficialLetterUa { get; set; }

    public int? IncidentReasonId { get; set; }

    public string? OfficialLetterIfpesToCcc { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;

    public virtual IncidentReason? IncidentReason { get; set; }
}