// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class InitialFormation
{
    public int EmployeeNumber { get; set; }

    public decimal? AverageGrade { get; set; }

    public bool? HasAdministrativeProcedure { get; set; }

    public string? OfficialLetterAdministrativeProcedure { get; set; }

    public bool? IsConsideredForLoc { get; set; }

    public int? CourseId { get; set; }

    public int? InitialFormationStatusId { get; set; }

    public virtual Course? Course { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;

    public virtual InitialFormationStatus? InitialFormationStatus { get; set; }
}