// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class InitialFormationStatus
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public virtual ICollection<InitialFormation> InitialFormations { get; set; } = new List<InitialFormation>();
}