// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class NationalMilitaryService
{
    public int EmployeeNumber { get; set; }

    public string ServiceNumber { get; set; } = null!;

    public DateOnly? IssuedDate { get; set; }

    public string? IssuedInstitution { get; set; }

    public bool? IsValidated { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;
}