// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class PayrollPositionRecord
{
    public int Id { get; set; }

    public int EmployeeNumber { get; set; }

    public int PayrollPositionId { get; set; }

    public DateTime? CreationDate { get; set; }

    public virtual PayrollRecord EmployeeNumberNavigation { get; set; } = null!;

    public virtual PayrollPosition PayrollPosition { get; set; } = null!;
}