// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class PayrollRecord
{
    public int EmployeeNumber { get; set; }

    public DateOnly? StartDate { get; set; }

    public bool? IsDirectDesignation { get; set; }

    public int? ProfessionalCareerServiceId { get; set; }

    public int? ProfessionalCareerServiceYear { get; set; }

    public string? AssignmentArea { get; set; }

    public DateOnly? PayrollPeriod { get; set; }

    public bool IsEnabled { get; set; }

    public int? PayrollBranchId { get; set; }

    public int? PaymentAreaId { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;

    public virtual PaymentArea? PaymentArea { get; set; }

    public virtual PayrollBranch? PayrollBranch { get; set; }

    public virtual ICollection<PayrollPositionRecord> PayrollPositionRecords { get; set; } = new List<PayrollPositionRecord>();

    public virtual ProfessionalCareerService? ProfessionalCareerService { get; set; }
}