// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class PerformanceEvaluation
{
    public int Id { get; set; }

    public int EmployeeNumber { get; set; }

    public decimal FinalTestScore { get; set; }

    public int PerformanceLevelId { get; set; }

    public DateOnly? AcknowledgementDate { get; set; }

    public DateOnly? UnitDeliveryDate { get; set; }

    public string? DeliveryLetter { get; set; }

    public string? Observations { get; set; }

    public string? IndividualActionPlan { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;

    public virtual PerformanceLevel PerformanceLevel { get; set; } = null!;
}