// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class PerformanceLevel
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public virtual ICollection<PerformanceEvaluation> PerformanceEvaluations { get; set; } = new List<PerformanceEvaluation>();
}