// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class RecruitmentNotice
{
    public int Id { get; set; }

    public int EmployeeNumber { get; set; }

    public bool? IsAdmissionByRecruitment { get; set; }

    public short? RecruitmentYear { get; set; }

    public bool? IsAdmissionByCfi { get; set; }

    public DateOnly? CfiAdmissionDate { get; set; }

    public bool? IsCfiFinished { get; set; }

    public DateOnly? CfiCompletionDate { get; set; }

    public string? OfficialLetterCgaJoined { get; set; }

    public DateOnly? CgaJoinedDate { get; set; }

    public DateOnly? DischargedDate { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;
}