// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EmployeeManagementSystem.Shared.Models;

public partial class Resume
{
    public int Id { get; set; }

    public int EmployeeNumber { get; set; }

    public string? OfficialLetterCeccRequest { get; set; }

    public string? OfficialLetterUaToIfpesRequest { get; set; }

    public string? OfficialLetterSent { get; set; }

    public DateOnly? SentDate { get; set; }

    public string? OfficialLetterCccPrograming { get; set; }

    public string? OfficialLetterRescheduling { get; set; }

    public string? OfficialLetterIfpesScheduling { get; set; }

    public string? OfficialLetterCccRequest { get; set; }

    public string? OfficialLetterIfpesToUa { get; set; }

    public string? OfficialLetterUaSent { get; set; }

    public string? OfficialLetterIncidence { get; set; }

    public string? OfficialLetterIfpesToCeccSent { get; set; }

    public string? OfficialLetterUaToIfpes { get; set; }

    public string? OfficialLetterTurn { get; set; }

    public string? OfficialLetterCccProgramation { get; set; }

    public string? OfficialLetterIfpesProgramation { get; set; }

    public string? AdministrativeUnit { get; set; }

    public string? OfficialLetterSendingNotification { get; set; }

    public DateOnly? SendingNotificationDate { get; set; }

    public string? Observations { get; set; }

    public virtual Employee EmployeeNumberNavigation { get; set; } = null!;
}