// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using EmployeeManagementSystem.Shared.Models;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagementSystem.Shared.Data;

public partial class EmployeeManagementContext : DbContext
{
    public EmployeeManagementContext(DbContextOptions<EmployeeManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdministrativeProcedure> AdministrativeProcedures { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<BasicPoliceSkill> BasicPoliceSkills { get; set; }

    public virtual DbSet<CeccResult> CeccResults { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<EccRescheduling> EccReschedulings { get; set; }

    public virtual DbSet<EccScheduling> EccSchedulings { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Incident> Incidents { get; set; }

    public virtual DbSet<IncidentReason> IncidentReasons { get; set; }

    public virtual DbSet<InitialFormation> InitialFormations { get; set; }

    public virtual DbSet<InitialFormationStatus> InitialFormationStatuses { get; set; }

    public virtual DbSet<MaritalStatus> MaritalStatuses { get; set; }

    public virtual DbSet<NationalMilitaryService> NationalMilitaryServices { get; set; }

    public virtual DbSet<PaymentArea> PaymentAreas { get; set; }

    public virtual DbSet<PayrollBranch> PayrollBranches { get; set; }

    public virtual DbSet<PayrollPosition> PayrollPositions { get; set; }

    public virtual DbSet<PayrollPositionRecord> PayrollPositionRecords { get; set; }

    public virtual DbSet<PayrollRecord> PayrollRecords { get; set; }

    public virtual DbSet<PerformanceEvaluation> PerformanceEvaluations { get; set; }

    public virtual DbSet<PerformanceLevel> PerformanceLevels { get; set; }

    public virtual DbSet<PoliceSkillStatus> PoliceSkillStatuses { get; set; }

    public virtual DbSet<ProfessionalCareerService> ProfessionalCareerServices { get; set; }

    public virtual DbSet<RecruitmentNotice> RecruitmentNotices { get; set; }

    public virtual DbSet<Resume> Resumes { get; set; }

    public virtual DbSet<State> States { get; set; }

    public virtual DbSet<UniquePoliceCertificate> UniquePoliceCertificates { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdministrativeProcedure>(entity =>
        {
            entity.HasKey(e => e.EmployeeNumber).HasName("PK__Administ__8D66359994EBB07D");

            entity.Property(e => e.EmployeeNumber).ValueGeneratedNever();
            entity.Property(e => e.OfficialLetter).HasMaxLength(50);

            entity.HasOne(d => d.EmployeeNumberNavigation).WithOne(p => p.AdministrativeProcedure)
                .HasForeignKey<AdministrativeProcedure>(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdministrativeProcedures_Employees");
        });

        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.PhoneNumber).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRole",
                    r => r.HasOne<AspNetRole>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUser>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("AspNetUserRoles");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<BasicPoliceSkill>(entity =>
        {
            entity.HasKey(e => e.EmployeeNumber).HasName("PK__BasicPol__8D6635990123E3EC");

            entity.Property(e => e.EmployeeNumber).ValueGeneratedNever();
            entity.Property(e => e.AverageGrade).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.OfficialLetter).HasMaxLength(50);

            entity.HasOne(d => d.EmployeeNumberNavigation).WithOne(p => p.BasicPoliceSkill)
                .HasForeignKey<BasicPoliceSkill>(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BasicPoliceSkills_Employees");

            entity.HasOne(d => d.PoliceSkillStatus).WithMany(p => p.BasicPoliceSkills)
                .HasForeignKey(d => d.PoliceSkillStatusId)
                .HasConstraintName("FK_BasicPoliceSkills_PoliceSkillStatuses");
        });

        modelBuilder.Entity<CeccResult>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CeccResu__3214EC0754049675");

            entity.Property(e => e.Notification).HasMaxLength(50);
            entity.Property(e => e.OfficialLetter).HasMaxLength(50);

            entity.HasOne(d => d.EmployeeNumberNavigation).WithMany(p => p.CeccResults)
                .HasForeignKey(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CeccResults_Employees");
        });

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Courses__3214EC07B0A13BF7");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(200);
            entity.Property(e => e.NormalizedName).HasMaxLength(200);
        });

        modelBuilder.Entity<EccRescheduling>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EccResch__3214EC070C0FF766");

            entity.ToTable("EccRescheduling");

            entity.Property(e => e.MedicalEvaluationDate).HasColumnType("datetime");
            entity.Property(e => e.OfficialLetterCenter).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterIfpesProgramation).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterRescheduling).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterReschedulingCecc).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterResult).HasMaxLength(50);
            entity.Property(e => e.PolygraphEvaluationDate).HasColumnType("datetime");
            entity.Property(e => e.PsychologicalEvaluationDate).HasColumnType("datetime");
            entity.Property(e => e.Results).HasMaxLength(50);
            entity.Property(e => e.SocioeconomicEnvironmentEvaluationDate).HasColumnType("datetime");
            entity.Property(e => e.ToxicologicalEvaluationDate).HasColumnType("datetime");

            entity.HasOne(d => d.EmployeeNumberNavigation).WithMany(p => p.EccReschedulings)
                .HasForeignKey(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EccRescheduling_Employees");
        });

        modelBuilder.Entity<EccScheduling>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EccSched__3214EC075E53798B");

            entity.ToTable("EccScheduling");

            entity.Property(e => e.MedicalEvaluationDate).HasColumnType("datetime");
            entity.Property(e => e.OfficialLetterCeyCc).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterIfpes).HasMaxLength(50);
            entity.Property(e => e.PolygraphEvaluationDate).HasColumnType("datetime");
            entity.Property(e => e.PsychologicalEvaluationDate).HasColumnType("datetime");
            entity.Property(e => e.SocioeconomicEnvironmentEvaluationDate).HasColumnType("datetime");
            entity.Property(e => e.ToxicologicalEvaluationDate).HasColumnType("datetime");

            entity.HasOne(d => d.EmployeeNumberNavigation).WithMany(p => p.EccSchedulings)
                .HasForeignKey(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EccScheduling_Employees");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC07218910D3");

            entity.HasIndex(e => e.ProfessionalLicense, "UQ__Employee__721610D7CB22EA29").IsUnique();

            entity.HasIndex(e => e.Cuip, "UQ__Employee__AFA91782636702E2").IsUnique();

            entity.HasIndex(e => e.Curp, "UQ__Employee__AFAC52E59782308A").IsUnique();

            entity.HasIndex(e => e.Rfc, "UQ__Employee__CAF0BCA6E019FBB4").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Address).HasMaxLength(80);
            entity.Property(e => e.BirthPlace).HasMaxLength(100);
            entity.Property(e => e.City).HasMaxLength(80);
            entity.Property(e => e.Cuip)
                .HasMaxLength(19)
                .IsUnicode(false);
            entity.Property(e => e.Curp)
                .HasMaxLength(19)
                .IsUnicode(false);
            entity.Property(e => e.DriverLicense)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.Email).HasMaxLength(200);
            entity.Property(e => e.EmergencyContact)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.HighestEducationLevel).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.LicenseType).HasMaxLength(20);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Neighborhood).HasMaxLength(60);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber2)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber3)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ProfessionalLicense)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Rfc)
                .HasMaxLength(13)
                .IsUnicode(false);
            entity.Property(e => e.Zip)
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.HasOne(d => d.LicenseIssuedState).WithMany(p => p.EmployeeLicenseIssuedStates)
                .HasForeignKey(d => d.LicenseIssuedStateId)
                .HasConstraintName("FK_Employees_LicenseIssuedStates");

            entity.HasOne(d => d.MaritalStatus).WithMany(p => p.Employees)
                .HasForeignKey(d => d.MaritalStatusId)
                .HasConstraintName("FK_Employees_MaritalStatuses");

            entity.HasOne(d => d.State).WithMany(p => p.EmployeeStates)
                .HasForeignKey(d => d.StateId)
                .HasConstraintName("FK_Employees_States");
        });

        modelBuilder.Entity<Incident>(entity =>
        {
            entity.HasKey(e => e.EmployeeNumber).HasName("PK__Incident__8D66359910FC9BC7");

            entity.Property(e => e.EmployeeNumber).ValueGeneratedNever();
            entity.Property(e => e.OfficialLetterAreaIncident).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterIfpesToCcc).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterUa).HasMaxLength(50);

            entity.HasOne(d => d.EmployeeNumberNavigation).WithOne(p => p.Incident)
                .HasForeignKey<Incident>(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Incidents_Employees");

            entity.HasOne(d => d.IncidentReason).WithMany(p => p.Incidents)
                .HasForeignKey(d => d.IncidentReasonId)
                .HasConstraintName("FK_Incidents_IncidentReasons");
        });

        modelBuilder.Entity<IncidentReason>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Incident__3214EC079ACE1890");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(60);
            entity.Property(e => e.NormalizedName).HasMaxLength(60);
        });

        modelBuilder.Entity<InitialFormation>(entity =>
        {
            entity.HasKey(e => e.EmployeeNumber).HasName("PK__InitialF__8D6635991DF8F483");

            entity.Property(e => e.EmployeeNumber).ValueGeneratedNever();
            entity.Property(e => e.AverageGrade).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.OfficialLetterAdministrativeProcedure).HasMaxLength(50);

            entity.HasOne(d => d.Course).WithMany(p => p.InitialFormations)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK_InitialFormations_Courses");

            entity.HasOne(d => d.EmployeeNumberNavigation).WithOne(p => p.InitialFormation)
                .HasForeignKey<InitialFormation>(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InitialFormations_Employees");

            entity.HasOne(d => d.InitialFormationStatus).WithMany(p => p.InitialFormations)
                .HasForeignKey(d => d.InitialFormationStatusId)
                .HasConstraintName("FK_InitialFormations_InitialFormationStatuses");
        });

        modelBuilder.Entity<InitialFormationStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__InitialF__3214EC07CF1C553F");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(150);
        });

        modelBuilder.Entity<MaritalStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MaritalS__3214EC0730B2E130");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<NationalMilitaryService>(entity =>
        {
            entity.HasKey(e => e.EmployeeNumber).HasName("PK__National__8D6635990C8B6836");

            entity.ToTable("NationalMilitaryService");

            entity.HasIndex(e => e.ServiceNumber, "UQ__National__B8FD3A770A41CDAE").IsUnique();

            entity.Property(e => e.EmployeeNumber).ValueGeneratedNever();
            entity.Property(e => e.IssuedInstitution).HasMaxLength(60);
            entity.Property(e => e.ServiceNumber).HasMaxLength(25);

            entity.HasOne(d => d.EmployeeNumberNavigation).WithOne(p => p.NationalMilitaryService)
                .HasForeignKey<NationalMilitaryService>(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NationalMilitaryService_Employees");
        });

        modelBuilder.Entity<PaymentArea>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentA__3214EC073E7987D3");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(150);
            entity.Property(e => e.NormalizedName).HasMaxLength(150);
        });

        modelBuilder.Entity<PayrollBranch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PayrollB__3214EC0734365421");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(150);
            entity.Property(e => e.NormalizedName).HasMaxLength(150);
        });

        modelBuilder.Entity<PayrollPosition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PayrollP__3214EC0765CF55A8");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(150);
            entity.Property(e => e.NormalizedName).HasMaxLength(150);
        });

        modelBuilder.Entity<PayrollPositionRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PayrollP__3214EC0784A9D181");

            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.EmployeeNumberNavigation).WithMany(p => p.PayrollPositionRecords)
                .HasForeignKey(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmployeeNumber");

            entity.HasOne(d => d.PayrollPosition).WithMany(p => p.PayrollPositionRecords)
                .HasForeignKey(d => d.PayrollPositionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayrollPosition");
        });

        modelBuilder.Entity<PayrollRecord>(entity =>
        {
            entity.HasKey(e => e.EmployeeNumber).HasName("PK__PayrollR__8D663599EF9E5D35");

            entity.Property(e => e.EmployeeNumber).ValueGeneratedNever();
            entity.Property(e => e.AssignmentArea).HasMaxLength(150);

            entity.HasOne(d => d.EmployeeNumberNavigation).WithOne(p => p.PayrollRecord)
                .HasForeignKey<PayrollRecord>(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayrollRecords_Employees");

            entity.HasOne(d => d.PaymentArea).WithMany(p => p.PayrollRecords)
                .HasForeignKey(d => d.PaymentAreaId)
                .HasConstraintName("FK_PayrollRecords_PaymentAreas");

            entity.HasOne(d => d.PayrollBranch).WithMany(p => p.PayrollRecords)
                .HasForeignKey(d => d.PayrollBranchId)
                .HasConstraintName("FK_PayrollRecords_PayrollBranches");

            entity.HasOne(d => d.ProfessionalCareerService).WithMany(p => p.PayrollRecords)
                .HasForeignKey(d => d.ProfessionalCareerServiceId)
                .HasConstraintName("FK_PayrollRecords_ProfessionalCareerServices");
        });

        modelBuilder.Entity<PerformanceEvaluation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Performa__3214EC07CACE221D");

            entity.ToTable("PerformanceEvaluation");

            entity.Property(e => e.DeliveryLetter).HasMaxLength(50);
            entity.Property(e => e.FinalTestScore).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.IndividualActionPlan).HasMaxLength(200);

            entity.HasOne(d => d.EmployeeNumberNavigation).WithMany(p => p.PerformanceEvaluations)
                .HasForeignKey(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PerformanceEvaluation_Employees");

            entity.HasOne(d => d.PerformanceLevel).WithMany(p => p.PerformanceEvaluations)
                .HasForeignKey(d => d.PerformanceLevelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PerformanceEvaluation_PerformanceLevels");
        });

        modelBuilder.Entity<PerformanceLevel>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Performa__3214EC07225734A1");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(40);
        });

        modelBuilder.Entity<PoliceSkillStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PoliceSk__3214EC076BF9BC66");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(40);
        });

        modelBuilder.Entity<ProfessionalCareerService>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Professi__3214EC07D8AE4BB4");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(150);
        });

        modelBuilder.Entity<RecruitmentNotice>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Recruitm__3214EC077DA21BD7");

            entity.Property(e => e.OfficialLetterCgaJoined).HasMaxLength(50);

            entity.HasOne(d => d.EmployeeNumberNavigation).WithMany(p => p.RecruitmentNotices)
                .HasForeignKey(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecruitmentNotices_Employees");
        });

        modelBuilder.Entity<Resume>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Resumes__3214EC07E74A0FC4");

            entity.Property(e => e.AdministrativeUnit).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterCccProgramation).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterCccPrograming).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterCccRequest).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterCeccRequest).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterIfpesProgramation).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterIfpesScheduling).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterIfpesToCeccSent).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterIfpesToUa).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterIncidence).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterRescheduling).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterSendingNotification).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterSent).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterTurn).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterUaSent).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterUaToIfpes).HasMaxLength(50);
            entity.Property(e => e.OfficialLetterUaToIfpesRequest).HasMaxLength(50);

            entity.HasOne(d => d.EmployeeNumberNavigation).WithMany(p => p.Resumes)
                .HasForeignKey(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Resumes_Employees");
        });

        modelBuilder.Entity<State>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__States__3214EC07CF0BB82F");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<UniquePoliceCertificate>(entity =>
        {
            entity.HasKey(e => e.EmployeeNumber).HasName("PK__UniquePo__8D6635994846D9BB");

            entity.Property(e => e.EmployeeNumber).ValueGeneratedNever();
            entity.Property(e => e.Certificate).HasMaxLength(50);

            entity.HasOne(d => d.EmployeeNumberNavigation).WithOne(p => p.UniquePoliceCertificate)
                .HasForeignKey<UniquePoliceCertificate>(d => d.EmployeeNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UniquePoliceCertificates_Employees");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}